### PR TITLE
Update to 1.20 and add Terraformers' biome mods.

### PR DESCRIPTION
**Pull request by gniftygnome**
- Update to 1.20.1; should work in 1.20; might in 1.20.2
- Support for Cinderscapes, Terrestria, and Traverse

This mod would really benefit from using datagen.  That would knock out half the little json files one has to maintain, and it would give recipe advancements.  I'm short on time at the moment but if this gets accepted I'll try and come back to it later.

With Material gone, I've guessed at the best map color for each anvil type.  Mostly this should be the same as before but the more custom anvils (like gemstones) are now closer to their real colors on maps.

Support for other third-party mods might need a quick review.  F.e. have they removed or added wood types.

### CODE REVIEW

**Comment by FirstMegaGame4** [comment]
Oh sorry, didn't saw your pull request.
This seems to be a great work thanks to you!

About using DataGen, yes agree with you, with all the new mod integrations it would be very nice to use it.
About the mapcolors, I trust you.
And I'll check if big mods like BYG changed their woodsets after your pull request.

I approve all this changes. I you have some questions or enhancement to suggest, please contact my on my Discord (my username equals to my github name but in lowercase).

**Comment by FirstMegaGame4** [comment]
Also, you can bump the Fabric Anvils version up to 4.0.0. Using the DataGen system will change lot of things for the json files, and for this little vanilla plus mod a change like this and a new major Minecraft version justifies it.

**Comment by FirstMegaGame4** [comment]
And finally, will this pull request receive new commits or it is ready to merge?

**Comment by gniftygnome** [comment]
This PR is ready to merge (as you mentioned, you will want to adjust the version to whatever you prefer).  I will look into datagen when I have a little time for it and file another PR if this one is already merged.

**Pull request merged**
